#################################
#  USER CONFIGURATION
#################################

MBUSPICO_DEVICE_KEY="XXXXXXXXXXXXXXXXXXX"

# LOGLEVEL
#  Controls the verbosity of message log output
#  Possible values:
MBUSPICO_LOG_LEVEL=0

# WIFI
#  Wifi options
MBUSPICO_WIFI_ENABLED=False
MBUSPICO_WIFI_SSID=""
MBUSPICO_WIFI_PWD=""
MBUSPICO_WIFI_HOSTNAME="MBusPico"

# UDP RECEIVER
MBUSPICO_UDP_ENABLED=False
MBUSPICO_UDP_RECEIVER_HOST=""
MBUSPICO_UDP_RECEIVER_PORT=0
MBUSPICO_UDP_INTERVAL_S=30

# HTTP SERVER
MBUSPICO_HTTP_ENABLED=True
MBUSPICO_HTTP_SERVER_PORT=80
MBUSPICO_HTTP_AUTH_USER=""
MBUSPICO_HTTP_AUTH_PWD=""